<a href="https://colab.research.google.com/github/ImadT/Fraud-detection/blob/main/Data_Cleaning_Part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sn

pd.set_option("display.max_rows", None)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
train = pd.read_csv("/content/drive/MyDrive/2020 2021/Projet ML/train_data.csv", sep=';')
print(train.shape)
train.head()

(590540, 181)

   TransactionID  V72  V124  V78    V127  ...  V66  V132   V130    D15  isFraud
0        2987000  0.0   1.0  1.0   117.0  ...  1.0   0.0    0.0    0.0        0
1        2987001  0.0   1.0  1.0     0.0  ...  1.0   0.0    0.0    0.0        0
2        2987002  0.0   1.0  1.0     0.0  ...  1.0   0.0    0.0  315.0        0
3        2987003  0.0   1.0  1.0  1758.0  ...  1.0  50.0  354.0  111.0        0
4        2987004  0.0   1.0  1.0     0.0  ...  1.0   0.0    0.0   52.0        0

[5 rows x 181 columns]

In [ ]:
train.drop('TransactionID', axis=1 ,inplace = True)

In [ ]:
# the categorical variables that steel exist in the train dataset after the preprocessing
categorical_columns = ['ProductCD']+[f'card{i}' for i in range(1, 7)] + ['addr1','addr2']
for i in train.columns:
  if i in categorical_columns:
    print(i)

card1
card3
card2
addr1
card5
ProductCD
card6
addr2
card4

In [ ]:
for catego in categorical_columns:
  print(catego)
  print(len(X[catego].value_counts()), '\n')

ProductCD
5

card1
13553

card2
500

card3
114

card4
4

card5
119

card6
4

addr1
332

addr2
74

So we need to get rid of the variables that takes a lot of values level

In [ ]:
column_to_delet = ['card1', 'card2', 'card3', 'card5', 'addr1', 'addr2']
X = X[[x for x in X.columns if x not in column_to_delet]]

In [ ]:
train['card6'].value_counts()

debit              441509
credit             148986
debit or credit        30
charge card            15
Name: card6, dtype: int64